### ISSUE TITLE
Wrong "status_plain" after Winter

### ISSUE THREAD

**Issue by jove01** [geertmeersman/robonect#144]
**Describe the bug**
In Winter time I had deactivated the integration. After activating starting the Integration and also after starting and stopping the automover in status_plain the content is "Mäht". But the automover is back in the docking station.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log information**
If possible activate debug logging on the component as mentioned below.

<https://www.home-assistant.io/integrations/logger/>

```yaml
logger:
  default: warning
  logs:
    custom_components.robonect: debug
```

**Additional context**
