### ISSUE TITLE
Changing timer from Service Call fail

### ISSUE THREAD

**Issue by BoneheadFraggle** [geertmeersman/robonect#68]
**Describe the bug**
When trying to modify a timer from a Service Call, the Service Call fails. See image below.

**To Reproduce**

1. Go to Dev Tools / Services
2. Click on Robonect: Modify a timer
3. Fill out the form

**Expected behavior**
The timer to be updated :-)

**Screenshots**
![image](https://github.com/geertmeersman/robonect/assets/2287810/f7d09017-a817-45b5-88ae-bdfb78efa02d)

**Log information**
If possible activate debug logging on the component as mentioned below.

```2023-08-06 18:16:30.535 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: value must be one of [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] for dictionary value @ data['timer']```

**Additional context**
I just tried to adjust it in YAML. The GUI proposes this (that doesn't work):
```
service: robonect.timer
data:
  timer: "1"
  enable: false
  entity_id: vacuum.automower_robonect
  start: "07:00:00"
  end: "22:00:00"
  weekdays:
    - mo
```
But if I change `timer: "1"` to `timer: 1` it accepts the service call - and it actually updates the timer as well.
So maybe a change of data type is needed?
